[package]
name = "akimi"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "akimi"
path = "src/main.rs"

[dependencies]
akimi-ext4 = { path = "../../crates/ext4" }
akimi-model = { path = "../../crates/model" }
anyhow.workspace = true
clap.workspace = true
serde_json.workspace = true

